PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'0001_01_01_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(4,'2025_11_01_101726_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(5,'2025_11_06_000000_create_footer_settings_table',1);
INSERT INTO migrations VALUES(6,'2025_11_06_170542_create_testimonials_table',2);
INSERT INTO migrations VALUES(7,'2025_11_06_172241_add_image_to_testimonials_table',3);
INSERT INTO migrations VALUES(8,'2025_11_07_000001_create_social_media_table',4);
INSERT INTO migrations VALUES(9,'2025_11_08_024832_create_contact_form_fields_table',4);
INSERT INTO migrations VALUES(10,'2025_11_08_131647_create_hero_sliders_table',4);
INSERT INTO migrations VALUES(11,'2025_11_08_161025_create_about_sections_table',4);
INSERT INTO migrations VALUES(12,'2025_11_08_163522_create_project_sections_table',4);
INSERT INTO migrations VALUES(13,'2025_11_08_174756_add_logo_to_project_sections_table',4);
INSERT INTO migrations VALUES(14,'2025_11_08_175735_create_our_projects_table',4);
INSERT INTO migrations VALUES(15,'2025_11_08_203721_create_bookings_table',4);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
INSERT INTO sessions VALUES('t9OjO6pCHOOsMqipQy9NDLOSLJToeukIQm0HGvD6',NULL,'127.0.0.1','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36','YTozOntzOjY6Il90b2tlbiI7czo0MDoiclJvMXU0T29NUE5JWFZTcHpxSlppS2VHcEhtQVZBNk1wbTBKdDM2YSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NDE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMS9hcGkvZm9vdGVyLXNldHRpbmdzIjtzOjU6InJvdXRlIjtzOjE5OiJhcGkuZm9vdGVyLXNldHRpbmdzIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==',1762511439);
INSERT INTO sessions VALUES('ZzK8VjtQ89hSr8Z1CUGd0sWlX4OGuY6yMfnUayOD',NULL,'127.0.0.1','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36','YTo1OntzOjY6Il90b2tlbiI7czo0MDoiaGFwcmNvU3BUWTc4a1NpeWx3WEp6VzhrQ09ra2VhTVdHUW96eUtUOSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mzg6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9hcGkvdGVzdGltb25pYWxzIjtzOjU6InJvdXRlIjtzOjIyOiJhcGkudGVzdGltb25pYWxzLmluZGV4Ijt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319czo4OiJpc19hZG1pbiI7YjoxO3M6MTE6ImFkbWluX2VtYWlsIjtzOjE1OiJhZG1pbkBnbWFpbC5jb20iO30=',1762511439);
INSERT INTO sessions VALUES('HzabYnwng6Bb68J1ozjEDGLes3KvZArAoUngx1Aw',NULL,'127.0.0.1','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36','YTo1OntzOjY6Il90b2tlbiI7czo0MDoiVkdnVkl2S3MwZG56aEh4VGhsWHJSSlViUDljbUdMUExVMmQySm9pbSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NDE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMS9hcGkvZm9vdGVyLXNldHRpbmdzIjtzOjU6InJvdXRlIjtzOjE5OiJhcGkuZm9vdGVyLXNldHRpbmdzIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319czo4OiJpc19hZG1pbiI7YjoxO3M6MTE6ImFkbWluX2VtYWlsIjtzOjE1OiJhZG1pbkBnbWFpbC5jb20iO30=',1762509048);
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" text not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "footer_settings" ("id" integer primary key autoincrement not null, "title" varchar, "description" text, "phone1" varchar, "phone2" varchar, "email" varchar, "project_address" text, "contact_address" text, "quick_links" text, "legal_links" text, "social_links" text, "map_url" varchar, "bottom_text" varchar, "qr_image_path" varchar, "qr_section_title" varchar, "map_button_text" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO footer_settings VALUES(1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[{"label":null,"href":null},{"label":null,"href":null},{"label":null,"href":null},{"label":null,"href":null},{"label":null,"href":null}]','[{"label":null,"href":null},{"label":null,"href":null}]','{"facebook":null,"instagram":null,"twitter":null,"linkedin":null,"youtube":null}',NULL,'u','footer/0ToXwhGVIUYUe4VLm9cUVxw0XGcUhokm8aAhG5to.png',NULL,NULL,'2025-11-06 13:19:04','2025-11-06 13:19:04');
CREATE TABLE IF NOT EXISTS "testimonials" ("id" integer primary key autoincrement not null, "avatar" varchar, "name" varchar not null, "title" varchar not null, "quote" text not null, "order" integer not null default '0', "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "image_path" varchar);
INSERT INTO testimonials VALUES(1,'d','gf','hg','g',0,1,'2025-11-07 10:19:54','2025-11-07 10:19:54','testimonials/7f8scp3TxClMoFrUXq81TKH35w2GCQLQC0Vil16N.jpg');
CREATE TABLE IF NOT EXISTS "social_media" ("id" integer primary key autoincrement not null, "platform" varchar not null, "title" varchar not null, "content" text, "link" varchar, "image_path" varchar, "order" integer not null default '0', "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "contact_form_fields" ("id" integer primary key autoincrement not null, "label" varchar not null, "type" varchar not null default 'text', "placeholder" varchar, "required" tinyint(1) not null default '0', "order" integer not null default '0', "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "hero_sliders" ("id" integer primary key autoincrement not null, "title" varchar, "subtitle" varchar, "description" text, "primary_button_text" varchar, "primary_button_link" varchar, "secondary_button_text" varchar, "secondary_button_link" varchar, "image_url" varchar, "order" integer not null default '0', "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "about_sections" ("id" integer primary key autoincrement not null, "section_key" varchar not null, "title" varchar, "subtitle" varchar, "content" text, "content_2" text, "content_3" text, "image_url" varchar, "name" varchar, "position" varchar, "extra_data" text, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "project_sections" ("id" integer primary key autoincrement not null, "section_key" varchar not null, "title" varchar, "subtitle" varchar, "content" text, "image_url" varchar, "extra_data" text, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "logo_url" varchar);
CREATE TABLE IF NOT EXISTS "our_projects" ("id" integer primary key autoincrement not null, "title" varchar not null, "description" text not null, "image_path" varchar not null, "cta_text" varchar not null default 'বিস্তারিত জানুন', "cta_link" varchar, "order" integer not null default '0', "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "bookings" ("id" integer primary key autoincrement not null, "name" varchar not null, "phone" varchar not null, "email" varchar not null, "plot_size" varchar, "message" text, "status" varchar not null default 'pending', "is_read" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('migrations',15);
INSERT INTO sqlite_sequence VALUES('footer_settings',1);
INSERT INTO sqlite_sequence VALUES('testimonials',1);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE INDEX "personal_access_tokens_expires_at_index" on "personal_access_tokens" ("expires_at");
CREATE UNIQUE INDEX "about_sections_section_key_unique" on "about_sections" ("section_key");
CREATE UNIQUE INDEX "project_sections_section_key_unique" on "project_sections" ("section_key");
COMMIT;
